// French, fr
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Ana Sayfa": `Page d'accueil`,
	"Hizmetlerimiz": `Nos services`,
	"Terapistler": `Thérapeutes`,
	"İletişim": `Contact`,
	"Giriş": `Se connecter`,
	"Kayıt Ol": `S'inscrire`,

	// Hero Section
	"Ruhsal İyilik Yolculuğunuza Başlayın" : `Commencez votre voyage de bien-être spirituel`,
	"Yapay zeka destekli eşleştirme sistemiyle, kişiselleştirilmiş ruh sağlığı desteği için uzman terapistlerle bağlantı kurun"
: `Entrez en contact avec des thérapeutes experts pour un soutien personnalisé en matière de santé mentale grâce à un système de correspondance alimenté par l'IA.`,
	"Aramıza Katıl": `Nous rejoindre`,
	"Daha Fazla Bilgi": `Plus d'informations`,

	// Services Section
	"Yapay Zeka Eşleştirmesi": `Mise en relation par intelligence artificielle`,
	"Gelişmiş yapay zeka sistemimiz, ihtiyaç ve tercihlerinizi analiz ederek size en uygun terapisti bulur.": `Notre système avancé d'intelligence artificielle analyse vos besoins et vos préférences pour trouver le thérapeute qui vous convient le mieux.`,
	"Güvenli Online Seanslar": `Séances en ligne sécurisées`,
	"Evinizin rahatlığında, güvenli görüntülü görüşme ve mesajlaşma yoluyla terapistinizle bağlantı kurun.": `Connectez-vous avec votre thérapeute depuis le confort de votre domicile grâce à des appels vidéo et des messages sécurisés.`,
	"İlerleme Takibi": `Suivi des progrès`,
	"Yapay zeka destekli içgörüler ve ilerleme raporlarıyla ruh sağlığı yolculuğunuzu takip edin.": `Suivez votre parcours de santé mentale grâce à des informations et des rapports de progrès alimentés par l'IA.`,

	// How İts Work Section
	"Nasıl Çalışır?": `Comment cela fonctionne-t-il `,
	"Hesabınızı oluşturun ve kısa bir değerlendirme yapın": `Créez votre compte et faites une brève évaluation`,
	"Eşleştirme": `Appariement`,
	"Yapay zekamız sizi uygun terapistlerle eşleştirir": `Notre intelligence artificielle vous met en relation avec des thérapeutes appropriés`,
	"Randevu Al": `Prendre un rendez-vous`,
	"Size uygun bir zamanda ilk seansınızı planlayın": `Planifiez votre première séance à l'heure qui vous convient.`,
	"Terapiye Başla": `Commencer la thérapie`,
	"Daha iyi bir ruh sağlığı için yolculuğunuza başlayın": `Commencez votre voyage vers une meilleure santé mentale`,

	// Therapist Section
	"Terapistler İçin" : `Pour les thérapeutes`,
	"Uzmanlığınıza uygun danışanlarla buluşmak ve pratiğinizi genişletmek için platformumuza katılın.": `Rejoignez notre plateforme pour rencontrer des clients dans votre spécialité et développer votre pratique.`,
	"Yapay zeka destekli danışan eşleştirmesi": `Recherche de clients assistée par l'intelligence artificielle`,
	"Esnek planlama": `Planification flexible`,
	"Güvenli ödeme sistemi": `Système de paiement sécurisé`,
	"Mesleki gelişim kaynakları": `Ressources de développement professionnel`,
	"Terapist Olarak Katıl": `Participer en tant que thérapeute`,

	// Footer
	"Yapay zeka destekli eşleştirme ile ruh sağlığı uzmanlarıyla sizi buluşturuyoruz.": `Nous vous mettons en contact avec des experts en santé mentale grâce à une mise en relation assistée par l'intelligence artificielle.`,
	"Hızlı Bağlantılar": `Liens rapides`,
	"Destek": `Support`,
	"Yardım Merkezi": `Centre d'aide`,
	"Gizlilik Politikası": `Politique de confidentialité`,
	"Tüm hakları saklıdır.": `Tous les droits sont réservés.`,






}