// French, fr
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Ana Sayfa": `Page d'accueil`,
	"Hizmetlerimiz": `Nos services`,
	"Terapistler": `Thérapeutes`,
	"İletişim": `Contact`,
	"Giriş": `Se connecter`,
	"Kayıt Ol": `S'inscrire`,

}