// Turkey, tr
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Ana Sayfa": `Ana Sayfa`,
	"Hizmetlerimiz": `Hizmetlerimiz`,
	"Terapistler": `Terapistler`,
	"İletişim": `İletişim`,
	"Giriş": `Giriş`,
	"Kayıt Ol": `Kayıt Ol`,

	// Hero Section
	"Ruhsal İyilik Yolculuğunuza Başlayın" : `Ruhsal İyilik Yolculuğunuza Başlayın
`,
	"Yapay zeka destekli eşleştirme sistemiyle, kişiselleştirilmiş ruh sağlığı desteği için uzman terapistlerle bağlantı kurun"
: `Yapay zeka destekli eşleştirme sistemiyle, kişiselleştirilmiş ruh sağlığı desteği için uzman terapistlerle bağlantı kurun
`,
	"Aramıza Katıl": `Aramıza Katıl`,
	"Daha Fazla Bilgi": `Daha Fazla Bilgi`,

	// Services Section
	"Yapay Zeka Eşleştirmesi": `Yapay Zeka Eşleştirmesi
`,
	"Gelişmiş yapay zeka sistemimiz, ihtiyaç ve tercihlerinizi analiz ederek size en uygun terapisti bulur.": `Gelişmiş yapay zeka sistemimiz, ihtiyaç ve tercihlerinizi analiz ederek size en uygun terapisti bulur.`,
	"Güvenli Online Seanslar": `Güvenli Online Seanslar`,
	"Evinizin rahatlığında, güvenli görüntülü görüşme ve mesajlaşma yoluyla terapistinizle bağlantı kurun.": `Evinizin rahatlığında, güvenli görüntülü görüşme ve mesajlaşma yoluyla terapistinizle bağlantı kurun.`,
	"İlerleme Takibi": `İlerleme Takibi`,
	"Yapay zeka destekli içgörüler ve ilerleme raporlarıyla ruh sağlığı yolculuğunuzu takip edin.": `Yapay zeka destekli içgörüler ve ilerleme raporlarıyla ruh sağlığı yolculuğunuzu takip edin.`,

	// How İts Work Section
	"Nasıl Çalışır?": `Nasıl Çalışır`,
	"Hesabınızı oluşturun ve kısa bir değerlendirme yapın": `Hesabınızı oluşturun ve kısa bir değerlendirme yapın`,
	"Eşleştirme": `Eşleştirme
`,
	"Yapay zekamız sizi uygun terapistlerle eşleştirir": `Yapay zekamız sizi uygun terapistlerle eşleştirir`,
	"Randevu Al": `Randevu Al`,
	"Size uygun bir zamanda ilk seansınızı planlayın": `Size uygun bir zamanda ilk seansınızı planlayın`,
	"Terapiye Başla": `Terapiye Başla
`,
	"Daha iyi bir ruh sağlığı için yolculuğunuza başlayın": `Daha iyi bir ruh sağlığı için yolculuğunuza başlayın`,

	// Therapist Section
	"Terapistler İçin" : `Terapistler İçin`,
	"Uzmanlığınıza uygun danışanlarla buluşmak ve pratiğinizi genişletmek için platformumuza katılın.": `Uzmanlığınıza uygun danışanlarla buluşmak ve pratiğinizi genişletmek için platformumuza katılın.`,
	"Yapay zeka destekli danışan eşleştirmesi": `Yapay zeka destekli danışan eşleştirmesi`,
	"Esnek planlama": `Esnek planlama`,
	"Güvenli ödeme sistemi": `Güvenli ödeme sistemi`,
	"Mesleki gelişim kaynakları": `Mesleki gelişim kaynakları`,
	"Terapist Olarak Katıl": `Terapist Olarak Katıl`,

	// Footer
	"Yapay zeka destekli eşleştirme ile ruh sağlığı uzmanlarıyla sizi buluşturuyoruz.": `Yapay zeka destekli eşleştirme ile ruh sağlığı uzmanlarıyla sizi buluşturuyoruz.`,
	"Hızlı Bağlantılar": `Hızlı Bağlantılar`,
	"Destek": `Destek`,
	"Yardım Merkezi": `Yardım Merkezi`,
	"Gizlilik Politikası": `Gizlilik Politikası`,
	"Tüm hakları saklıdır.": `Tüm hakları saklıdır.`,

	// Contact Page
	"Sorularınız için bizimle iletişime geçebilirsiniz. Size en kısa sürede dönüş yapacağız.": `Sorularınız için bizimle iletişime geçebilirsiniz. Size en kısa sürede dönüş yapacağız.`,
	"İletişim Bilgileri": `İletişim Bilgileri`,
	"Adres": `Adres`,
	"Telefon": `Telefon`,
	"E-posta": `E-posta`,
	"Bize Ulaşın": `Bize Ulaşın`,
	"Ad": `Ad`,
	"Soyad": `Soyad`,
	"Mail": `Mail`,
	"Mesaj": `Mesaj`,
	"Gönder": `Gönder`,

	// Privacy Page
	"Gizlilik Politikası": `Gizlilik Politikası`,
	"1. Veri Toplama ve Kullanım": `1. Veri Toplama ve Kullanım `,
	"Therapify olarak, kullanıcılarımızın gizliliğini korumayı taahhüt ediyoruz. Bu politika, hangi verileri topladığımızı ve nasıl kullandığımızı açıklar.": `Therapify olarak, kullanıcılarımızın gizliliğini korumayı taahhüt ediyoruz. Bu politika, hangi verileri topladığımızı ve nasıl kullandığımızı açıklar.

`,
	"Kişisel bilgiler (ad, soyad, e-posta)": `Kişisel bilgiler (ad, soyad, e-posta)`,
	"İletişim bilgileri": `İletişim bilgileri`,
	"Profil bilgileri": `Profil bilgileri`,
	"Kullanım verileri": `Kullanım verileri`,
	"2. Veri Güvenliği": `2. Veri Güvenliği`,
	"Verilerinizi korumak için endüstri standardı güvenlik önlemleri kullanıyoruz:": `Verilerinizi korumak için endüstri standardı güvenlik önlemleri kullanıyoruz:`,
	"SSL şifreleme": `SSL şifreleme`,
	"Güvenli veri depolama": `Güvenli veri depolama`,
	"Düzenli güvenlik güncellemeleri": `Düzenli güvenlik güncellemeleri`,
	"Erişim kontrolü": `Erişim kontrolü`,
	"3. Çerezler ve İzleme": `3. Çerezler ve İzleme`,
	"Hizmetlerimizi iyileştirmek için çerezler ve benzer teknolojiler kullanıyoruz:": `Hizmetlerimizi iyileştirmek için çerezler ve benzer teknolojiler kullanıyoruz:`,
	"Oturum çerezleri": `Oturum çerezleri`,
	"Tercih çerezleri": `Tercih çerezleri`,
	"Analitik çerezler": `Analitik çerezler`,
	"4. Veri Paylaşımı": `4. Veri Paylaşımı`,
	"Verilerinizi üçüncü taraflarla yalnızca aşağıdaki durumlarda paylaşırız:": `Verilerinizi üçüncü taraflarla yalnızca aşağıdaki durumlarda paylaşırız:`,
	"Yasal zorunluluk durumunda": `Yasal zorunluluk durumunda`,
	"Açık rızanız olduğunda": `Açık rızanız olduğunda`,
	"Hizmet sağlayıcılarımızla (veri işleme)": `Hizmet sağlayıcılarımızla (veri işleme)`,
	"5. Kullanıcı Hakları": `5. Kullanıcı Hakları`,
	"KVKK kapsamında aşağıdaki haklara sahipsiniz:": `KVKK kapsamında aşağıdaki haklara sahipsiniz:`,
	"Verilerinize erişim hakkı": `Verilerinize erişim hakkı`,
	"Verilerinizi düzeltme hakkı": `Verilerinizi düzeltme hakkı`,
	"Verilerinizin silinmesini talep etme hakkı": `Verilerinizin silinmesini talep etme hakkı`,
	"Veri işlemeye itiraz etme hakkı": `Veri işlemeye itiraz etme hakkı`,
	"Gizlilik politikamızla ilgili sorularınız için:": `Gizlilik politikamızla ilgili sorularınız için:
`,




}