// Turkey, tr
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Ana Sayfa": `Ana Sayfa`,
	"Hizmetlerimiz": `Hizmetlerimiz`,
	"Terapistler": `Terapistler`,
	"İletişim": `İletişim`,
	"Giriş": `Giriş`,
	"Kayıt Ol": `Kayıt Ol`,

}