// English, en-US
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Ana Sayfa": `Home Page`,
	"Hizmetlerimiz": `Our Services`,
	"Terapistler": `Therapists`,
	"İletişim": `Contact`,
	"Giriş": `Login`,
	"Kayıt Ol": `Register`,

}