// English, en-US
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Ana Sayfa": `Home Page`,
	"Hizmetlerimiz": `Our Services`,
	"Terapistler": `Therapists`,
	"İletişim": `Contact`,
	"Giriş": `Login`,
	"Kayıt Ol": `Register`,

	// Hero Section
	"Ruhsal İyilik Yolculuğunuza Başlayın" : `Start Your Journey to Spiritual Well-Being`,
	"Yapay zeka destekli eşleştirme sistemiyle, kişiselleştirilmiş ruh sağlığı desteği için uzman terapistlerle bağlantı kurun"
: `Connect with expert therapists for personalized mental health support with an AI-powered matching system`,
	"Aramıza Katıl": `Join Us`,
	"Daha Fazla Bilgi": `More Information`,

	// Services Section
	"Yapay Zeka Eşleştirmesi": `Artificial Intelligence Matching`,
	"Gelişmiş yapay zeka sistemimiz, ihtiyaç ve tercihlerinizi analiz ederek size en uygun terapisti bulur.": `Our advanced artificial intelligence system analyzes your needs and preferences to find the most suitable therapist for you.`,
	"Güvenli Online Seanslar": `Secure Online Sessions`,
	"Evinizin rahatlığında, güvenli görüntülü görüşme ve mesajlaşma yoluyla terapistinizle bağlantı kurun.": `Connect with your therapist from the comfort of your home via secure video calling and messaging.`,
	"İlerleme Takibi": `Progress Tracking`,
	"Yapay zeka destekli içgörüler ve ilerleme raporlarıyla ruh sağlığı yolculuğunuzu takip edin.": `Track your mental health journey with AI-powered insights and progress reports.`,

	// How İts Work Section
	"Nasıl Çalışır?": `How it works`,
	"Hesabınızı oluşturun ve kısa bir değerlendirme yapın": `Create your account and make a short evaluation`,
	"Eşleştirme": `Pairing`,
	"Yapay zekamız sizi uygun terapistlerle eşleştirir": `Our artificial intelligence matches you with suitable therapists`,
	"Randevu Al": `Make an Appointment`,
	"Size uygun bir zamanda ilk seansınızı planlayın": `Schedule your first session at a time convenient for you`,
	"Terapiye Başla": `Start Therapy`,
	"Daha iyi bir ruh sağlığı için yolculuğunuza başlayın": `Start your journey to better mental health`,

	// Therapist Section
	"Terapistler İçin" : `For Therapists`,
	"Uzmanlığınıza uygun danışanlarla buluşmak ve pratiğinizi genişletmek için platformumuza katılın.": `Join our platform to meet clients in your specialty and expand your practice.`,
	"Yapay zeka destekli danışan eşleştirmesi": `Artificial intelligence assisted client matching`,
	"Esnek planlama": `Flexible planning`,
	"Güvenli ödeme sistemi": `Secure payment system`,
	"Mesleki gelişim kaynakları": `Professional development resources`,
	"Terapist Olarak Katıl": `Participate as a Therapist`,

	// Footer
	"Yapay zeka destekli eşleştirme ile ruh sağlığı uzmanlarıyla sizi buluşturuyoruz.": `We bring you together with mental health experts with artificial intelligence-supported matching.`,
	"Hızlı Bağlantılar": `Quick Links`,
	"Destek": `Support`,
	"Yardım Merkezi": `Help Center`,
	"Gizlilik Politikası": `Privacy Policy`,
	"Tüm hakları saklıdır.": `All rights reserved.`,

	// Contact Page
	"Sorularınız için bizimle iletişime geçebilirsiniz. Size en kısa sürede dönüş yapacağız.": `You can contact us for your questions. We will get back to you as soon as possible.`,
	"İletişim Bilgileri": `Contact Information`,
	"Adres": `Address`,
	"Telefon": `Telephone`,
	"E-posta": `Email`,
	"Bize Ulaşın": `Contact us`,
	"Ad": `Name`,
	"Soyad": `Surname`,
	"Mail": `Mail`,
	"Mesaj": `Message`,
	"Gönder": `Send`,

	// Privacy Page
	"Gizlilik Politikası": `Privacy Policy`,
	"1. Veri Toplama ve Kullanım": `1. Data Collection and Use `,
	"Therapify olarak, kullanıcılarımızın gizliliğini korumayı taahhüt ediyoruz. Bu politika, hangi verileri topladığımızı ve nasıl kullandığımızı açıklar.": `At Therapify, we are committed to protecting the privacy of our users. This policy explains what data we collect and how we use it.`,
	"Kişisel bilgiler (ad, soyad, e-posta)": `Personal information (name, surname, e-mail)`,
	"İletişim bilgileri": `Contact details`,
	"Profil bilgileri": `Profile information`,
	"Kullanım verileri": `Usage data`,
	"2. Veri Güvenliği": `2. Data Security`,
	"Verilerinizi korumak için endüstri standardı güvenlik önlemleri kullanıyoruz:": `We use industry-standard security measures to protect your data:`,
	"SSL şifreleme": `SSL encryption`,
	"Güvenli veri depolama": `Secure data storage`,
	"Düzenli güvenlik güncellemeleri": `Regular security updates`,
	"Erişim kontrolü": `Access control`,
	"3. Çerezler ve İzleme": `3. Cookies and Tracking`,
	"Hizmetlerimizi iyileştirmek için çerezler ve benzer teknolojiler kullanıyoruz:": `We use cookies and similar technologies to improve our services:`,
	"Oturum çerezleri": `Session cookies`,
	"Tercih çerezleri": `Preference cookies`,
	"Analitik çerezler": `Analytical cookies`,
	"4. Veri Paylaşımı": `4. Data Sharing`,
	"Verilerinizi üçüncü taraflarla yalnızca aşağıdaki durumlarda paylaşırız:": `We will only share your data with third parties in the following cases:`,
	"Yasal zorunluluk durumunda": `In case of legal obligation`,
	"Açık rızanız olduğunda": `With your explicit consent`,
	"Hizmet sağlayıcılarımızla (veri işleme)": `With our service providers (data processing)`,
	"5. Kullanıcı Hakları": `5. User Rights`,
	"KVKK kapsamında aşağıdaki haklara sahipsiniz:": `You have the following rights under KVKK:`,
	"Verilerinize erişim hakkı": `Right of access to your data`,
	"Verilerinizi düzeltme hakkı": `Right to rectify your data`,
	"Verilerinizin silinmesini talep etme hakkı": `Right to request deletion of your data`,
	"Veri işlemeye itiraz etme hakkı": `Right to object to data processing`,
	"Gizlilik politikamızla ilgili sorularınız için:": `For questions about our privacy policy:`,




}