// German, de
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Ana Sayfa": `Hauptseite`,
	"Hizmetlerimiz": `Unsere Dienstleistungen`,
	"Terapistler": `Therapeuten`,
	"İletişim": `Kontakt`,
	"Giriş": `Anmeldung`,
	"Kayıt Ol": `Anmelden`,

}