// This file was auto-generated by Quasalang

import tr from './tr'
import enUS from './en-US'
import de from './de'
import fr from './fr'

export default { 
	'tr': tr, // Turkey
	'en-US': enUS, // English
	'de': de, // German
	'fr': fr, // French
}